// Original, workplace-safe phrases. Each category has twelve distinct excuses.
export const phrases = {
  deployment: [
    "The deployment passed rehearsal and requested a stunt double for production.",
    "The release arrived on time. Its dependencies are still finding parking.",
    "The deployment is waiting for the server to finish its dramatic entrance.",
    "The release notes say smooth landing. The landing gear has requested clarification.",
    "The deploy button has confidence. The health check has follow-up questions.",
    "The release is technically live and emotionally still in staging.",
    "Our rollback plan has achieved the rare status of being read before the incident.",
    "The canary found a problem and would like its consulting fee in seeds.",
    "The release was ready until production introduced itself.",
    "We shipped the fix. The monitoring dashboard is deciding whether to clap.",
    "The deployment arrived wearing a parachute. This is considered progress.",
    "The server accepted the release but declined to endorse its lifestyle.",
  ],
  build: [
    "The compiler found a typo and promoted it to a company-wide announcement.",
    "The build is assembling a committee to discuss the missing semicolon.",
    "The artifacts are ready; the build is negotiating custody.",
    "The compiler is proofreading a novel we thought was a configuration file.",
    "The build cache remembers a different version of reality.",
    "The bundle got smaller after we removed the feature that made it work.",
    "The build system asked for a dependency and received a family reunion.",
    "One warning invited its friends and now the terminal needs chairs.",
    "The clean build is clean because it contains no artifacts yet.",
    "The compiler rejected the argument that it worked yesterday.",
    "Our build pipeline is a conveyor belt with trust issues.",
    "The source maps know where the problem is. They are being dramatic about it.",
  ],
  production: [
    "Production interpreted the happy path as an optional scenic route.",
    "The server is performing an unscheduled demonstration of our recovery plan.",
    "Production has requested that our assumptions submit identification.",
    "Production has discovered an edge case shaped exactly like our largest customer.",
    "The incident is stable. Our coffee consumption is scaling horizontally.",
    "The dashboards are green because the broken metric stopped reporting.",
    "Production read the happy-path test and chose creative freedom.",
    "The service is healthy in the same way a husky is quiet before stealing a sock.",
    "We have narrowed the cause to the part of the system currently existing.",
    "The fallback works. It has been promoted to the main plan without a ceremony.",
    "The alert arrived before the customer email. We are counting that as a win.",
    "Our recovery estimate is being reviewed by the concept of time.",
  ],
  bug: [
    "The edge case moved to the center and brought furniture.",
    "That variable has been exploring career opportunities outside its scope.",
    "The bug declined to reproduce until the screen-sharing session began.",
    "The bug is intermittent, which is engineer for witness protection.",
    "The reproduction is minimal. The emotional damage is not.",
    "The issue disappeared while screen sharing and returned to clock in afterward.",
    "The edge case has built a small apartment in the main path.",
    "We found the bug. It was wearing a feature flag as a disguise.",
    "The fix is one line. The explanation requires a whiteboard and snacks.",
    "The bug survived three refactors and now qualifies for seniority.",
    "The stack trace has provided directions to a place we never wanted to visit.",
    "The defect is resolved in the branch where optimism is enabled.",
  ],
  api: [
    "The API sent a response, but it used the envelope for the payload.",
    "The endpoint is observing a moment of silence for our timeout setting.",
    "The contract was clear. The response preferred interpretive dance.",
    "The endpoint returned success with the confidence of an empty response body.",
    "The API contract and implementation are currently seeing other people.",
    "The request timed out while the server composed a thoughtful silence.",
    "The response schema evolved during the meeting about freezing the schema.",
    "The retry succeeded in creating the same problem twice.",
    "The status code is correct. The payload is expressing itself artistically.",
    "The endpoint is idempotent on days when nobody asks it twice.",
    "The client sent a request. The server returned a character development arc.",
    "The integration test has discovered that both sides mean something different by optional.",
  ],
  database: [
    "The database is taking a full-table stroll to consider our question.",
    "The query asked for one row and accidentally invited the whole neighborhood.",
    "The migration packed the columns but forgot the forwarding address.",
    "The query planner chose the scenic route through every row.",
    "The migration passed locally on a database containing exactly our confidence.",
    "The index exists. The query would prefer to meet all the data personally.",
    "The connection pool is full of connections discussing their retirement.",
    "The transaction is waiting on a lock that is waiting on a conversation.",
    "The backup completed. We are now attempting the bold sequel: restore.",
    "The schema is flexible because we forgot where it was documented.",
    "The slow query has enough history to apply for heritage status.",
    "The data is consistent about disagreeing with the application.",
  ],
  deadline: [
    "The estimate included coding time, but the calendar added plot twists.",
    "The deadline arrived before the requirements finished introducing themselves.",
    "The last ten percent has applied for its own project manager.",
    "The estimate included development, testing and a completely fictional Tuesday.",
    "The smallest deliverable grew after someone used the word just.",
    "The timeline assumed dependencies would arrive with their shoes on.",
    "We can deliver quickly if the definition of delivered stops moving.",
    "The calendar is immutable. The scope is doing parkour.",
    "The critical path has stopped to attend a planning meeting.",
    "The deadline is realistic in the timezone where requirements never change.",
    "We reduced the scope. It is now only moderately larger than the week.",
    "The schedule has a buffer. Unfortunately it is written in pencil.",
  ],
  testing: [
    "The test fixture has developed stronger opinions than the specification.",
    "The flaky test only accepts results delivered under a full cache.",
    "The assertion expected certainty; the asynchronous task offered suspense.",
    "The test passed because the assertion was exceptionally supportive.",
    "The fixture describes a world with fewer users and better manners.",
    "The flaky test is conducting a long-term study of team patience.",
    "Coverage went up after we tested the part that says hello.",
    "The integration test has introduced the units to each other. They are arguing.",
    "The mock is perfect at simulating the service we wish we had.",
    "The regression test passed and immediately asked why it was not here earlier.",
    "The test suite is green. The skipped tests are enjoying a quiet holiday.",
    "The failing test has a point and an unfortunate way of making it.",
  ],
  network: [
    "The packets took a detour to admire the routing table.",
    "DNS is still deciding which address feels most like home.",
    "The connection is buffering its explanation for the delay.",
    "DNS is resolving everything except the team's uncertainty.",
    "The packet took a detour through a router with strong opinions.",
    "The connection is stable between the moments when it is not.",
    "The firewall followed the rules. The configuration forgot to read them.",
    "The timeout was selected by someone who believed all servers live next door.",
    "The service is reachable from everywhere except the place that needs it.",
    "The proxy is helping by changing the question before it arrives.",
    "The request is in transit and has started a travel blog.",
    "The network is technically up. The route is considering its options.",
  ],
  "merge-conflict": [
    "Both branches brought a solution and neither brought a seating chart.",
    "Git discovered that two correct answers wanted the same line.",
    "The branches agree on the goal and disagree on every comma.",
    "Both branches improved the same line in incompatible directions.",
    "The conflict is resolved. The naming debate is still open.",
    "Git found two versions of the truth and asked us to facilitate.",
    "The rebase succeeded after we explained time travel to the tests.",
    "The diff is small if you exclude the file everybody reformatted.",
    "The merge was automatic until the humans got involved.",
    "The branch is current with main and several unresolved feelings.",
    "We chose both changes. The compiler would like us to choose again.",
    "The conflict marker survived review by pretending to be punctuation.",
  ],
  demo: [
    "The demo saw an audience and switched from software to performance art.",
    "The prototype is saving its best behavior for the recording we forgot to start.",
    "The live demo has added a surprise question to the presentation.",
    "The demo works best when the audience is a test fixture.",
    "The projector has detected confidence and activated its troubleshooting mode.",
    "The live demo is a distributed system consisting of nerves and Wi-Fi.",
    "The happy path worked until someone clicked the interesting button.",
    "The offline fallback is now the star of the presentation.",
    "The demo data is realistic enough to have missing fields.",
    "The browser refreshed and introduced us to the unsaved version.",
    "The feature worked backstage. It is negotiating public appearances.",
    "The rehearsal was flawless. The room has different opinions about networking.",
  ],
};
